### ISSUE TITLE
Creating and adding a second Window with Dim objects - doesn't show until resize

### ISSUE THREAD

**Issue by kierenj** [migueldeicaza/gui.cs#1414]
A have a main `Window` added to `Application.Top`, and a `TableView` added to it. The table has a `CellActivated` event which creates a new `Window`, also added to `Application.Top`.

If I set the `Width` and `Height` of the new window to anything calculated, e.g. `Dim.Fill()`, it will not show on the screen until I resize the terminal. Keypresses, table item selection etc work as normal, and the new window does not show.

If I set the dimensions of the new window to anything constant, e.g. `20` each, it will show immediately.

Putting the `Dim.Fill()`-ed window creation in a timeout or main-thread invoke do not fix the situation.

## Edit
It works if I parent the new `Window` to the existing one. I wondered if it could be a Z-order issue, but when I shrunk the first window and had the second one larger, it didn't show until resize, either

**Comment by tznind** [comment]
Hi, this is not a part of the API I am familiar with but I have tried to reproduce your issue:

```csharp
Application.Init();

var win = new Window(){
    Width = Dim.Fill(),
    Height = Dim.Fill()
};

var btn = new Button("press me");
btn.Clicked += ()=>{

    var win2 = new Window(){
        Y = 10,
        Width = Dim.Fill(),
        Height = Dim.Fill()
    };

    Application.Top.Add(win2);

};
win.Add(btn);

Application.Top.Add(win);
Application.Run();
Application.Shutdown();
```

![image](https://user-images.githubusercontent.com/31306100/128593503-1e8385d4-ffc7-4b03-8fbb-123356874369.png)
_After button is pressed_

I think the top `Window` still has the full size of the UI since you can see there is no bottom corners and bottom line to the top window.

**Comment by BDisp** [comment]
> I think Dim.Fill() seems to go all the way to the bottom of the screen regardless of any other Window/View controls below. So Fill is to fill the space in the parent control (not fill up to the next view).
> 
> You might be able to use percentages to achieve what you want: `Height = Dim.Percent(50)`


This is normal behavior because `Dim.Fill` will always fill the entire size of the superview. Another solution is using the `Dim.Percent`.

**Comment by BDisp** [comment]
> It works if I parent the new `Window` to the existing one. I wondered if it could be a Z-order issue, but when I shrunk the first window and had the second one larger, it didn't show until resize, either

It will be good if you can show the code you are using. As you are using a `TableView`, maybe something is not updating the view layout. Sometimes, it's not enough call only `SetNeedsDisplay` and is also needed call the `SetNeedsLayout`. The reason for this is in the `View.Redraw` method where the `LayoutSubviews` is only called if the `LayoutNeeded` is true.

**Comment by kierenj** [comment]
Here's a minimal example. With `Dim`, the new window does not appear until I resize. With constants, it appears immediately:

https://github.com/kierenj/gui.cs-issue-1414

**Comment by kierenj** [comment]
(I can find no `SetNeedsLayout` in the published version - I'll try the repro with the main branch version)

**Comment by kierenj** [comment]
On `main`, it works first time, no need for `SetNeedsLayout`.

**Comment by BDisp** [comment]
Please, always try running the current main branch in the cases where the published version fail. After the issue persist, so report please. Try with the current main branch, because I think that was a bug in the layout subviews already fixed.

**Comment by BDisp** [comment]
Ok I already seen and there are some bug. I'll try to fix it and tell something here when done. Thanks.

![one](https://user-images.githubusercontent.com/13117724/128602042-9211d630-a822-44c5-b102-b784b6ff4564.png)![hello](https://user-images.githubusercontent.com/13117724/128602047-661158b6-b2fb-4c0d-b30b-561dc8ebc79f.png)

**Comment by BDisp** [comment]
Thanks for your report @kierenj. I already fixed in the PR #1385 and I appreciate if you can test it.

![one](https://user-images.githubusercontent.com/13117724/128785403-bf70b5b2-8fcd-4482-a1d5-13ae91028597.png)![hello](https://user-images.githubusercontent.com/13117724/128785434-da1417c2-d92c-4f8d-acba-6948499a2def.png)

**Comment by tim-elmer** [comment]
It's entirely possible I'm doing something incorrectly, but I'm still experiencing this behavior while referencing the current main branch (618714cc). My UI tree is the same as originally described, except I'm using a plain View rather than a TableView (`Top -> Window -> View`). I'm removing the current View and adding a new one to the Window on a button click event. The newly added view shows up only if I resize the window.

On a side note, scaling the window vertically breaks reflow in the Windows console, Windows Terminal works fine.

**Comment by BDisp** [comment]
This example https://github.com/kierenj/gui.cs-issue-1414 don't uses `TableView`, but since the views are inside a `Window` or a `Toplevel`, it must work now. Otherwise, share your code to see what is going on.

**Comment by tim-elmer** [comment]
Not sure why I deleted the comment, gut reaction when I got it working I suppose. Sorry about that @BDisp. 🤦‍♂️

I restructured from `Application` -> `Window` -> `View` to `Application` -> `TopLevel` -> `Window` -> `View` (where the `View` is removed/replaced from/to the `Window`) and now it works as expected. Can probably chalk it up to unfamiliarity with the library. That said, if there's a better way to structure things, I'm all ears.

The issue with the Windows Console breaking reflow when resized vertically remains, but I'd hazard that's more a limitation of the Windows Console than the library.

**Comment by BDisp** [comment]
> 
> 
> Not sure why I deleted the comment, gut reaction when I got it working I suppose. Sorry about that @BDisp. 🤦‍♂️
> 
No problem.

> I restructured from `Application` -> `Window` -> `View` to `Application` -> `TopLevel` -> `Window` -> `View` (where the `View` is removed/replaced from/to the `Window`) and now it works as expected. Can probably chalk it up to unfamiliarity with the library. That said, if there's a better way to structure things, I'm all ears.
> 
To maintain the menu and status bar always visible in the application, you need to add the views to a `Window` and then add it to the `Application.Top`, or add the views to a `Toplevel` and then add it to the `Application.Top`.

> The issue with the WindowsConsole breaking reflow when resized vertically remains, but I'd hazard that's more a limitation of the Windows Console than the library.

Yes, is a limitation of the `WindowsConsole`, which returns always the same height on shrinking, causing the menu or the status bar not visible on scrolling.
