### ISSUE TITLE
Driver "v2win" broken in `conhost`

### ISSUE THREAD

**Issue by GitHubThor** [migueldeicaza/gui.cs#4004]
Hello, 

Driver "v2win" is broken in version v2.0.0-develop.4401 when used in Console Host. It happens inside de VS IDE and now it also happens running it outside the IDE in Windows Explorer.

It shows escape codes along with a wrong rendering.

![Image](https://github.com/user-attachments/assets/ba607ca6-a29b-45f3-ae06-63eee2408ba5)

Remapping the glyphs does not fix the issue, so seems not related to glyphs.

WindowsDriver works.

_Originally posted by @GitHubThor in https://github.com/gui-cs/Terminal.Gui/discussions/4003_

**Comment by BDisp** [comment]
The more strange is v2net not rendering the glyphs as the v2win does using `Windows Terminal`. This worth to being investigate.

**Comment by tig** [comment]
> The more strange is v2net not rendering the glyphs as the v2win does using `Windows Terminal`. This worth to being investigate.

I agree. But this issues title and description says nothing about that.

**Comment by BDisp** [comment]
> I agree. But this issues title and description says nothing about that.

It's in the discussion #4003 as OP mention above.

**Comment by GitHubThor** [comment]
> If there are other "escape codes" problems beyond what you described in the other post, that was cleared up becaues you were not calling `Shutdown`, please let me know.

Let me explain this, sorry for the language barrier. I do use Shutdown and Shutdown is not related with this issue, neither making it better.

Today I tested both 2.0.0-develop.4401 and 2.0.0-prealpha.1895, both same issue only when running **inside VS with conhost** and  "v2win" driver. (conhost is the only way to go when application requires admin privileges in windows)

"WindowsDriver" seems to work well now both 2.0.0-develop.4401 and 2.0.0-prealpha.1895.  "v2win" driver is not working!

Yesterday I was using 2.0.0-v2-develop.2203 since it appeared as the latest in nuget. In that version yesterday was the opposite, "WindowsDriver" was not working inside VS with conhost and "v2win" was not even accepted driver.

I hope this helps, don't hesitate to ask me fore more clarifications if needed.

BTW: I'm still confused of what versions to use 2.0.0-develop.YYYY or 2.0.0-prealpha.YYYY, independently of what VS Nuget manager offers in the list. Thanks!

**Comment by tig** [comment]
Just use the `2.0.0-develop.YYYY` with the highest YYYY number.

**Comment by tig** [comment]
It is very challenging trying to keep track of multiple topics when they are scattered throughout Discussions and Issues. 

@GitHubThor: Would you please:

a) Update the title of this Issue with a more precise description of the issue. If it only happens in v2win, state that.
b) Update the 1st post in this Issue with a screenshot, GIF, or other evidence that shows the behavior you are seeing.

**Comment by BDisp** [comment]
> I don't understand why nuget is even showing 2203. That version is NOT listed on Nuget.

I think nuget it's using the user cached local package.

**Comment by GitHubThor** [comment]
> From this image, there is nothing wrong with the Glyphs. This is due to something else. Not sure what.

Agreed, I tried next remapping and did not fix or change anything:

{
        "Themes": [
                  {
                  "Default": {
                  "Glyphs.ULCorner": "",
                  "Glyphs.URCorner": "",
                  "Glyphs.LLCorner": "",
                  "Glyphs.LRCorner": "",
                  "Glyphs.HLine": "-",
                  "Glyphs.VLine": "|"
                  }
        }
    ]
}

**Comment by GitHubThor** [comment]
BTW, just tested, TerminalGuiDesigner.exe using 2.0.0-develop.4400 has the same issue inside and outside the VS IDE. Detected too when used with conhost terminal:

![Image](https://github.com/user-attachments/assets/825b6175-2c96-4f83-bbd5-dcfd48023b6a)

**Comment by tig** [comment]
I've reproduced v2win not working in conhost:

![Image](https://github.com/user-attachments/assets/946d020d-fe7e-44d3-9a4b-e7c77498e1d8)

@GitHubThor for now, I recommend you just use "WindowsDriver". It works fine in Conhost as long as you remap the glyphs as I've shown in 

- #4006

**Comment by tznind** [comment]
Please can you run the latest TGD and upload the generated logs. This will show trace logging from conhost and we might be able to see why it releases the escape codes.

Logs appear in %appdata% in TerminalGuiDesigner folder logs subdir.

You can run designer with `-d WindowsDriver`

**Comment by tig** [comment]
> Please can you run the latest TGD and upload the generated logs. This will show trace logging from conhost and we might be able to see why it releases the escape codes.
> 
> Logs appear in %appdata% in TerminalGuiDesigner folder logs subdir.
> 
> Incidentally, you can still run designer with `-d WindowsDriver`
> 
> The v2 drivers are still very new so this kind of feedback is very helpful!

@tznind this repros on all TG apps. It has nothing to do with TGD.

As noted in another issue, for users running in `conhost` they should use `NetDriver`.

Yes, we should see if we can make v2win/v2net work in `conhost` as well.

**Comment by GitHubThor** [comment]
> Please can you run the latest TGD and upload the generated logs. This will show trace logging from conhost and we might be able to see why it releases the escape codes.

My logs using v2win:

[logfile20250329.zip](https://github.com/user-attachments/files/19522326/logfile20250329.zip)

I will use NetDriver from now on, works well. This is just in case it helps, although

 seems to me nothing interesting in the logs.

**Comment by BDisp** [comment]
> From this image, there is nothing wrong with the Glyphs. This is due to something else. Not sure what.

This is due the conhost.exe or cmd.exe doesn't support escape sequence to save/restore the terminal. Thus, if it isn't a WT then escape sequences must be avoid. Perhaps may need to have a separate issue for that.

**Comment by tznind** [comment]
interesting, the mouse input came direct to console screen not to input processor.  There is literally nothing read from input stream.  How odd.

> This is due the conhost.exe or cmd.exe doesn't support escape sequence to save/restore the terminal. 

Its more like for the v2win it is deciding to send mouse sequences direct to the output stream instead of input 😕

**Comment by tznind** [comment]
@tig what version of conhost? Do I just hit start menu and type conhost? when I do that I get a terminal that seems to work fine with v2win...

**Comment by BDisp** [comment]
You can experience that by two ways:

1 - Set WT to Windows Console Host and start debugging --driver v2win from VS2022.
2 - Open VS2022 as admin and start debugging --driver v2win.

**Comment by tznind** [comment]
I have tried both of these things and do not get any corruption... 

To be clear I just have to run admin mode vs and run UICatalog and move mouse - I should instantly see ansi codes fill up all over screen?

@tig did you also do anything special?

This si the version I am running 
```
PS C:\Windows\System32> (Get-Item "C:\Windows\System32\conhost.exe").VersionInfo.FileVersion
10.0.19041.320 (WinBuild.160101.0800)
```

**Comment by tznind** [comment]
Ok I can reproduce, you have to tick this to cause the breakage:

![Image](https://github.com/user-attachments/assets/0693d1ea-0186-4c33-aead-b3a2baa62e6d)

**Comment by tznind** [comment]
For v2net it crash on startup

Here is logs with `-dl Trace`

```
2025-03-30 10:28:19.041 +01:00 [INF] Main Loop Coordinator booting...
2025-03-30 10:28:19.059 +01:00 [INF] Creating NetOutput
2025-03-30 10:28:19.062 +01:00 [INF] Creating NetInput
2025-03-30 10:28:19.063 +01:00 [FTL] NetWinVTConsole could not be constructed i.e. could not configure terminal modes. May indicate running in non-interactive session e.g. unit testing CI
System.ApplicationException: Failed to set input console mode, error code: 87.
   at Terminal.Gui.NetWinVTConsole..ctor() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\NetDriver\NetWinVTConsole.cs:line 54
   at Terminal.Gui.NetInput..ctor() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\NetInput.cs:line 26
2025-03-30 10:28:19.070 +01:00 [FTL] Input loop crashed
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.set_TreatControlCAsInput(Boolean value)
   at Terminal.Gui.NetInput..ctor() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\NetInput.cs:line 38
   at Terminal.Gui.ApplicationV2.<>c.<.ctor>b__7_0() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\ApplicationV2.cs:line 28
   at Terminal.Gui.MainLoopCoordinator`1.RunInput() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\MainLoopCoordinator.cs:line 105
```

This is the crash:
```
[?1049h[?25l[?1003h[?1015h[?1006hUnhandled exception. System.AggregateException: One or more errors occurred. (One
or more errors occurred. (The parameter is incorrect.))
 ---> System.AggregateException: One or more errors occurred. (The parameter is incorrect.)adPoolThread)
 ---> System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.set_TreatControlCAsInput(Boolean value)os\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\MainLoopCo
   at Terminal.Gui.NetInput..ctor() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\NetInput.cs:line 38
   at Terminal.Gui.ApplicationV2.<>c.<.ctor>b__7_0() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\Application
2.cs:line 28.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at Terminal.Gui.MainLoopCoordinator`1.RunInput() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\MainLoopCoor
inator.cs:line 105ding.Tasks.Task.Wait()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executi
nContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---ver driver, String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\Co
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executi
nContext, ContextCallback callback, Object state)r driver, String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\Appl
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---evel() in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 323
   at Terminal.Gui.MainLoopCoordinator`1.StartAsync() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\MainLoopCo
rdinator.cs:line 89atalogApp.Main(String[] args) in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 234
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Terminal.Gui.ApplicationV2.CreateDriver(String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2
ApplicationV2.cs:line 110talog>clear
   at Terminal.Gui.ApplicationV2.Init(IConsoleDriver driver, String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\Co
soleDrivers\V2\ApplicationV2.cs:line 73
   at Terminal.Gui.Application.Init(IConsoleDriver driver, String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\Appl
cation\Application.Initialization.cs:line 47 -d v2net
   at UICatalog.UICatalogApp.RunUICatalogTopLevel() in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 323curred. (One
   at UICatalog.UICatalogApp.UICatalogMain(Options options) in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 450
   at UICatalog.UICatalogApp.Main(String[] args) in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 234
 ---> System.IO.IOException: The parameter is incorrect.
D:\Repos\temp\gui.cs\UICatalog>atControlCAsInput(Boolean value)
   at Terminal.Gui.NetInput..ctor() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\NetInput.cs:line 38
   at Terminal.Gui.ApplicationV2.<>c.<.ctor>b__7_0() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\Application
2.cs:line 28
   at Terminal.Gui.MainLoopCoordinator`1.RunInput() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\MainLoopCoor
inator.cs:line 105
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executi
nContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executi
nContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at Terminal.Gui.MainLoopCoordinator`1.StartAsync() in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2\MainLoopCo
rdinator.cs:line 89
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Terminal.Gui.ApplicationV2.CreateDriver(String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\ConsoleDrivers\V2
ApplicationV2.cs:line 110
   at Terminal.Gui.ApplicationV2.Init(IConsoleDriver driver, String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\Co
soleDrivers\V2\ApplicationV2.cs:line 73
   at Terminal.Gui.Application.Init(IConsoleDriver driver, String driverName) in D:\Repos\temp\gui.cs\Terminal.Gui\Appl
cation\Application.Initialization.cs:line 47
   at UICatalog.UICatalogApp.RunUICatalogTopLevel() in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 323
   at UICatalog.UICatalogApp.UICatalogMain(Options options) in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 450
   at UICatalog.UICatalogApp.Main(String[] args) in D:\Repos\temp\gui.cs\UICatalog\UICatalog.cs:line 234
```

**Comment by GitHubThor** [comment]
> Ok I can reproduce, you have to tick this to cause the breakage:

It crashes on my side without the legacy console enabled:

![Image](https://github.com/user-attachments/assets/13c92f02-979d-4cef-8a72-b4755a107c99)

**Comment by tznind** [comment]
> It crashes on my side without the legacy console enabled:

what do you get running
```
PS C:\Windows\System32> (Get-Item "C:\Windows\System32\conhost.exe").VersionInfo.FileVersion
```

**Comment by GitHubThor** [comment]
> PS C:\Windows\System32> (Get-Item "C:\Windows\System32\conhost.exe").VersionInfo.FileVersion

I get an error but the version shows:

![Image](https://github.com/user-attachments/assets/b6a6c7d7-82b8-4980-941b-35b41a6ceff3)

Also here there are the cmd.exe details:

![Image](https://github.com/user-attachments/assets/1274e08f-54b4-4e35-862b-7c52874552eb)

**Comment by BDisp** [comment]
> what do you get running
> 
> ```
> PS C:\Windows\System32> (Get-Item "C:\Windows\System32\conhost.exe").VersionInfo.FileVersion
> ```

Mine is:

`10.0.26100.2308 (WinBuild.160101.0800)`

**Comment by BDisp** [comment]
> Ok I can reproduce, you have to tick this to cause the breakage:
> 
> ![Image](https://github.com/user-attachments/assets/0693d1ea-0186-4c33-aead-b3a2baa62e6d)

This is the properties window of the Command Prompt (cmd.exe). You also need to check the conhost.exe properties window.

**Comment by BDisp** [comment]
@GitHubThor you only need to write in a pwsh this command and not the whole line `PS C:\Windows\System32>` is the prompt:

`(Get-Item "C:\Windows\System32\conhost.exe").VersionInfo.FileVersion`

**Comment by GitHubThor** [comment]
> [@GitHubThor](https://github.com/GitHubThor) you only need to write in a pwsh this command and not the whole line `PS C:\Windows\System32>` is the prompt:

Done:

PS C:\> (Get-Item "C:\Windows\System32\conhost.exe").VersionInfo.FileVersion
10.0.26100.1 (WinBuild.160101.0800)

I also have terminal settings at settings like this:

![Image](https://github.com/user-attachments/assets/2c58cefa-01dc-4398-bb25-ff83bdef3902)

**Comment by tznind** [comment]
Interesting now that I have turned on the v2 mode and turned it off again I still see error with turned off 😕

**Comment by tznind** [comment]
Think this is to do with the Force16Colors code, I remember running into this odd code branch and not replicating it when porting win render code.  I will investigate further

**Comment by tznind** [comment]
Ok I am unable to reproduce a termninal that works for WindowsDriver but not v2 without clicking the 'Use legacy console' checkbox

**Comment by BDisp** [comment]
> Think this is to do with the Force16Colors code, I remember running into this odd code branch and not replicating it when porting win render code. I will investigate further

You're right. If Force16Colors is true, due to not support true color, then the driver must avoid sending escape sequences to the terminal, even the ones that save and restore the terminal defaults.

**Comment by OptimusPi** [comment]
How can I help with this issue? I can test stuff. I am getting great graphics I’m on I think v2-develop-4xxx something

**Comment by BDisp** [comment]
> How can I help with this issue? I can test stuff. I am getting great graphics I’m on I think v2-develop-4xxx something

You can test my PR #4421 and check it.
